### ISSUE TITLE
Trouble with build

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/tt#13]
@freebroccolo I'm having trouble building now; I get the following when I run `make`:

```
Error: External library "ppx_jane" not found.
-> required by "tests/jbuild (context default)"
Hint: try: jbuilder external-lib-deps --missing @install
make: *** [build] Error 1
```

I tried running the command it suggests but that didn't help. Any ideas?

**Comment by jonsterling** [comment]
Update: I managed to get it to install dependencies, but first I had to run `opam uninstall tt`... Might just be a weirdness of opam, not sure.

**Comment by ghost** [comment]
Ah, usually I think an `opam upgrade` would fix this because the version would have been bumped. But doing the `uninstall` and re-pinning should work otherwise. Sorry for that.

**Comment by jonsterling** [comment]
No problem!

One thing I'm having trouble with now is that merlin is showing me a million errors that come from `base`. Any ideas how to fix that?

**Comment by ghost** [comment]
Let me download and try. Sometimes if you do some reorganizing and rebuild, merlin doesn't automatically get refreshed like it should. There's a mechanism in place that tries to detect when the `.merlin` files get modified and restart when that happens but it's not 100% reliable.

What should always work is a quick reload of the vscode window (which restarts the server). Fastest way to do that is to pull up the command palette (cmd+P and start typing `reload`). There should be a `reload window` command. See if that helps.

**Comment by ghost** [comment]
So just to be clear, when you run `make` and it invokes jbuilder, it's jbuilder that is automatically generating or updating the `.merlin` files. The editor mode tries to watch those and refresh merlin diagnostics when it happens but at the moment it's still a little unreliable (though it should be improved after some upcoming refactors to the language server).

**Comment by ghost** [comment]
Okay, so I just pulled from your PR and opened up a fresh editor window and I'm not seeing any merlin errors (after doing a `make clean` and `make build`). So I suspect it was just a bad diagnostics state that the window reload that I described above would fix.

**Comment by jonsterling** [comment]
Reloading the window fixed it! Thanks! 😄
